_target_: topobenchmarkx.models.network_module.NetworkModule

feature_encoder:
  _target_: topobenchmarkx.models.encoders.default_encoders.BaseFeatureEncoder
  in_channels: ${infer_in_channels:${dataset}} # ${dataset.parameters.num_features}
  out_channels: 32

backbone:
  _target_: topomodelx.nn.simplicial.sccn.SCCN
  channels: ${model.feature_encoder.out_channels}
  max_rank: 1
  n_layers: 1
  update_func: "sigmoid"

backbone_wrapper:
  _target_: topobenchmarkx.models.wrappers.default_wrapper.SCCNNWrapper
  _partial_: true
  out_channels: ${model.feature_encoder.out_channels}
  num_cell_dimensions: ${infere_list_length:${model.feature_encoder.in_channels}}

readout:
  _target_: topobenchmarkx.models.readouts.readout.AbstractReadOut
  readout_name: PropagateSignalDown #  Use <None> in case readout is not needed
  hidden_dim: ${model.feature_encoder.out_channels}
  num_cell_dimensions: ${infere_list_length:${model.feature_encoder.in_channels}}

head_model:
  _target_: topobenchmarkx.models.head_model.models.DefaultHead
  task_level: ${dataset.parameters.task_level}
  in_channels: ${model.feature_encoder.out_channels}
  out_channels: ${dataset.parameters.num_classes}
  pooling_type: sum

loss:
  _target_: topobenchmarkx.models.losses.loss.DefaultLoss
  task: ${dataset.parameters.task}
  loss_type: ${dataset.parameters.loss_type}

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01 #0.01
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.PolynomialLR
  _partial_: true
  last_epoch: -1
  total_iters: ${trainer.max_epochs}

# compile model for faster training with pytorch 2.0
compile: false
