_target_: modules.transforms.data_transform.DataTransform
transform_type: 'lifting'
transform_name: "CellCycleLifting"
max_cell_length: null
preserve_edge_attr: ${oc.select:parameters.preserve_edge_attr_if_lifted,False}
feature_lifting: SumLifting
