_target_: topobenchmark.transforms.data_transform.DataTransform
transform_type: 'lifting'
transform_name: "DiscreteConfigurationComplexLifting"
k: 2
feature_aggregation: "concat"
feature_lifting: ProjectionSum

# Required for all liftings to make the pipeline executable 
complex_dim: 3
preserve_edge_attr: ${oc.select:dataset.parameters.preserve_edge_attr_if_lifted,False}
neighborhoods: ${oc.select:model.backbone.neighborhoods,null}
