_target_: topobenchmark.transforms.data_transform.DataTransform
transform_type: 'lifting'
transform_name: "SimplicialDnDLifting"
complex_dim: 6
preserve_edge_attr: False
signed: True
feature_lifting: ProjectionSum
