_target_: topobenchmark.transforms.data_transform.DataTransform
transform_type: 'lifting'
transform_name: "SimplicialEccentricityLifting"
complex_dim: 3
preserve_edge_attr: False
signed: True
feature_lifting: ProjectionSum