_target_: topobenchmark.transforms.data_transform.DataTransform
transform_type: 'lifting'
transform_name: "LatentCliqueLifting"
signed: True
feature_lifting: ProjectionSum
edge_prob_mean: 0.95
edge_prob_var: 0.0001
# Required for all liftings to make the pipeline executable 
complex_dim: ${oc.select:dataset.parameters.max_dim_if_lifted,3}
preserve_edge_attr: ${oc.select:dataset.parameters.preserve_edge_attr_if_lifted,False}
neighborhoods: ${oc.select:model.backbone.neighborhoods,null}