_target_: topobenchmarkx.models.network_module.NetworkModule

model_name: alldeepset

feature_encoder:
  _target_: topobenchmarkx.models.encoders.default_encoders.BaseFeatureEncoder
  in_channels: ${infer_in_channels:${dataset}} #${dataset.parameters.num_features}
  out_channels: 32

backbone:
  _target_: topomodelx.nn.hypergraph.allset.AllSet
  in_channels: ${model.feature_encoder.out_channels}
  hidden_channels: ${model.feature_encoder.out_channels}
  n_layers: 1
  layer_dropout: 0.25
  mlp_num_layers: 2
  mlp_dropout: 0.0
  mlp_activation:
    _target_: torch.nn.ReLU
    _partial_: true
  mlp_norm:
    _target_: torch.nn.BatchNorm1d
    _partial_: true
    #num_features: ${model.backbone.hidden_channels}

backbone_wrapper:
  _target_: topobenchmarkx.models.wrappers.HypergraphWrapper
  _partial_: true
  wrapper_name: HypergraphWrapper
  out_channels: ${model.feature_encoder.out_channels}
  num_cell_dimensions: ${infere_list_length:${model.feature_encoder.in_channels}}

readout:
  _target_: topobenchmarkx.models.readouts.readout.AbstractReadOut
  readout_name: None #  Use <None> in case readout is not needed
  hidden_dim: None
  num_cell_dimensions: None

head_model:
  _target_: topobenchmarkx.models.head_model.models.DefaultHead
  task_level: ${dataset.parameters.task_level}
  in_channels: ${model.feature_encoder.out_channels}
  out_channels: ${dataset.parameters.num_classes}
  pooling_type: sum

loss:
  _target_: topobenchmarkx.models.losses.loss.DefaultLoss
  task: ${dataset.parameters.task}
  loss_type: ${dataset.parameters.loss_type}

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 50
  gamma: 0.5

# compile model for faster training with pytorch 2.0
compile: false
