_target_: topobenchmarkx.models.network_module.NetworkModule

model_name: unignn2

feature_encoder:
  _target_: topobenchmarkx.models.encoders.default_encoders.BaseNodeFeatureEncoder
  in_channels: ${dataset.parameters.num_features}
  out_channels: ${model.backbone.hidden_channels}

backbone:
  _target_: topomodelx.nn.hypergraph.unigcnii.UniGCNII
  in_channels: ${model.backbone.hidden_channels}  # ${dataset.parameters.num_features}
  hidden_channels: 64
  n_layers: 1
  alpha: 0.5
  beta: 0.5
  input_drop: 0.2
  layer_drop: 0.2

loss:
  _target_: topobenchmarkx.models.losses.loss.DefaultLoss
  task: ${dataset.parameters.task}
  loss_type: ${dataset.parameters.loss_type}
# evaluator:
#   _target_: topobenchmarkx.evaluators.evaluator.Evaluator
#   metrics: [acc, rocauc]

readout:
  _target_: topobenchmarkx.models.readouts.default_readouts.GNNBatchReadOut
  task_level: ${dataset.parameters.task_level}
  in_channels: ${model.backbone.hidden_channels}
  out_channels: ${dataset.parameters.num_classes}

backbone_wrapper:
  _target_: topobenchmarkx.models.wrappers.default_wrapper.HypergraphWrapper
  _partial_: true

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 50
  gamma: 0.5

# compile model for faster training with pytorch 2.0
compile: false
