_target_: topobenchmarkx.evaluators.evaluator.TorchEvaluator
metric_names: [mae, mse] #, precision, recall
task: ${dataset.parameters.task}
task_level: ${dataset.parameters.task_level}
num_classes: ${dataset.parameters.num_classes}


