# _target_: topobenchmarkx.data.loaders.GraphLoader


# defaults:
#   - transforms: ${get_default_transform:graph,${model}}

# # Data definition
# parameters:
#   data_domain: hypergraph
#   data_type: coauthorship
#   data_name: citeseer
#   data_dir: ${paths.data_dir}/${dataset.parameters.data_domain}/${dataset.parameters.data_type}/${dataset.parameters.data_name}
#   data_split_dir: ${paths.data_dir}/data_splits/${dataset.parameters.data_name}

#   # Dataset parameters
#   num_features: 3703
#   num_classes: 6
#   task: classification
#   loss_type: cross_entropy
#   monitor_metric: accuracy
#   task_level: node
#   data_seed: 0
#   split_type: random #'k-fold' # either k-fold or test
#   k: 10 # for k-Fold Cross-Validation

#   # Dataloader parameters
#   batch_size: 1 # Fixed
#   num_workers: 0
#   pin_memory: False

  
# Dataset loader config
loader:
  _target_: topobenchmarkx.data.loaders.HypergraphLoader
  parameters: 
    data_domain: hypergraph
    data_type: coauthorship
    data_name: citeseer
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  num_features: 3703
  num_classes: 6
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: node

#splits
split_params:
  learning_setting: transductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random #'k-fold' # either "k-fold" or "random" strategies
  k: 10 # for "k-fold" Cross-Validation
  train_prop: 0.5 # for "random" strategy splitting

# Dataloader parameters
dataloader_params:
  batch_size: 1 # Fixed
  num_workers: 1
  pin_memory: False
