_target_: topobenchmarkx.transforms.data_transform.DataTransform
transform_name: "InfereKNNConnectivity"
transform_type: "data manipulation"
args:
  k: 3 # Number of nearest neighbors to consider
  cosine: false # If true, will use the cosine distance instead of euclidean distance to find nearest neighbors. (Note: option equal to true gives an error)
  loop: true # If True, the graph will contain self-loops.

