# Defines the default parameters of the implemented transform.
_target_: topobenchmark.transforms.data_transform.DataTransform
transform_type: 'lifting'
transform_name: "SimplicialPathsLifting"
d1: 1
d2: 1
q: 1
i: 1
j: 2
complex_dim: 2
chunk_size: 1024
threshold: 4
preserve_edge_attr: False