loader:
  _target_: topobenchmarkx.data.loaders.SimplicialLoader
  parameters: 
    data_domain: simplicial
    data_type: topological 
    data_name: MANTRA
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}
    manifold_dim: 2
    version: "v0.0.5"
    target_name: "betti_numbers"

# Data definition
parameters:
  num_features: 1
  num_classes: 3


  # Dataset parameters
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: graph 
  data_seed: 0

  # Dataloader parameters
  batch_size: 128 # Needs to be divisible by the number of devices (e.g., if in a distributed setup)
  # train_val_test_split: [55_000, 5_000, 10_000]
  num_workers: 0
  pin_memory: False

#splits
split_params:
  learning_setting: inductive 
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random #'k-fold' # either "k-fold" or "random" strategies
  k: 10 # for "k-fold" Cross-Validation
  train_prop: 0.5 # for "random" strategy splitting
