_target_: topobenchmarkx.models.network_module.NetworkModule

backbone:
  _target_: topomodelx.nn.cell.cwn.CWN
  in_channels_0: ${dataset.parameters.num_features}
  in_channels_1: ${dataset.parameters.num_features}
  in_channels_2: ${dataset.parameters.num_features}
  hid_channels: 16
  n_layers: 4
  #dropout: 0.5
  #heads: 3
  #concat: True
  #skip_connection: True
  #att_lift: False

loss:
  _target_: topobenchmarkx.models.losses.loss.DefaultLoss
  task: ${dataset.parameters.task}

readout:
  _target_: topobenchmarkx.models.readouts.default_readouts.NodeLevelReadOut
  task_level: ${dataset.parameters.task_level}
  in_channels: ${model.backbone.hid_channels}
  out_channels: ${dataset.parameters.num_classes}

backbone_wrapper:
  _target_: topobenchmarkx.models.wrappers.default_wrapper.CWNWrapper
  _partial_: true

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.PolynomialLR
  _partial_: true
  last_epoch: -1
  total_iters: ${trainer.max_epochs}

# compile model for faster training with pytorch 2.0
compile: false
