# READ THIS TO UNDERSTAND THE CONFIGURATION FORMAT: https://hydra.cc/docs/advanced/overriding_packages/#using-a-config-group-more-than-once
_target_: topobenchmarkx.transforms.transformchain.TransformChain

defaults:
 - data_manipulations@first_time_call_DM: identity
 - data_manipulations@second_time_call_DM: graph_node_degrees
 - graph2simplicial: simplicial_clique
 #- /transforms/data_manipulations@data_fields_to_dense/data_fields_to_dense
