_target_: topobenchmarkx.transforms.transformchain.TransformChain

defaults:
 - graph2hypergraph: hypergraph_khop
 - feature_liftings@fourth_time_call_DM: base_lifting

# transform1:
#   _target_: topobenchmarkx.transforms.lifting.DataLiftingTransform
#   type: "Null Lifting (Identity)"
#   lifting: "Identity"


# transform2:
#   _target_: topobenchmarkx.transforms.lifting.DataLiftingTransform
#   lifting: "HypergraphKHopLifting"
#   k_value: 1