_target_: topobenchmarkx.io.load.loaders.HypergraphLoader

# defaults:
#   - transforms/graph2hypergraph: hypergraph_khop

#   - transforms/feature_liftings: base_lifting
# Data definition
parameters:
  data_domain: hypergraph
  data_type: coauthorship
  data_name: Cora
  data_dir: ${paths.data_dir}${dataset.parameters.data_domain}/${dataset.parameters.data_type}/${dataset.parameters.data_name}
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.parameters.data_name}

  # Dataset parameters
  num_features: 1433
  num_classes: 7
  task: classification
  task_level: node
  data_seed: 0

  # Dataloader parameters
  batch_size: 128 # Needs to be divisible by the number of devices (e.g., if in a distributed setup)
  # train_val_test_split: [55_000, 5_000, 10_000]
  num_workers: 0
  pin_memory: False
