_target_: topobenchmarkx.io.load.loaders.GraphLoader


defaults:
  - /transforms/transform_chain1

# Data definition
parameters:
  data_domain: graph
  data_type: cocitation
  data_name: Cora
  data_dir: ${paths.data_dir}${dataset.parameters.data_domain}/${dataset.parameters.data_type}/${dataset.parameters.data_name}
  data_split_dir: ${paths.data_dir}data_splits/${dataset.parameters.data_name}/train_prop=0.5

  # Dataset parameters
  num_features: 1433
  num_classes: 7
  task: classification
  task_level: node
  data_seed: 0

  # Dataloader parameters
  batch_size: 128 # Needs to be divisible by the number of devices (e.g., if in a distributed setup)
  num_workers: 0
  pin_memory: False
