_target_: topobenchmarkx.io.load.loaders.GraphLoader


defaults:
  - transforms: ${get_default_transform:graph,${model}}

# Data definition
parameters:
  data_domain: graph
  data_type: cocitation
  data_name: PubMed
  data_dir: ${paths.data_dir}${dataset.parameters.data_domain}/${dataset.parameters.data_type}/${dataset.parameters.data_name}
  data_split_dir: ${paths.data_dir}data_splits/${dataset.parameters.data_name}

  # Dataset parameters
  num_features: 500
  num_classes: 3
  task: classification
  loss_type: cross_entropy
  task_level: node
  data_seed: 0
  split_type: k-fold #'k-fold' # either k-fold or test
  k: 10 # for k-Fold Cross-Validation

  # Dataloader parameters
  batch_size: 1 # Fixed
  num_workers: 0
  pin_memory: False
