_target_: topobenchmarkx.io.load.loaders.GraphLoader


defaults:
  - transforms/graph2hypergraph: hypergraph_khop
  #- transforms/graph2simplicial: simplicial_clique
  - transforms/feature_liftings: base_lifting

# Data definition
parameters:
  data_domain: graph
  data_type: cocitation
  data_name: Cora
  data_dir: ${paths.data_dir}${dataset.parameters.data_domain}/${dataset.parameters.data_type}
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.parameters.data_name}

  # Dataset parameters
  num_features: 1433
  num_classes: 7
  task: classification
  task_level: node
  data_seed: 0
  split_type: test #'k-fold' # either k-fold or test
  k: 10 # for k-Fold Cross-Validation

  # Dataloader parameters
  batch_size: 10 # Needs to be divisible by the number of devices (e.g., if in a distributed setup)
  num_workers: 0
  pin_memory: False
