_target_: topobenchmarkx.io.load.loaders.ManualGraphLoader

defaults:
  #- transforms/data_manipulations@transforms.keep_connected_component: keep_connected_component
  - transforms: ${get_default_transform:graph,${model}}
  - transforms/data_manipulations: node_degrees
  - transforms/data_manipulations@transforms.simplicial_curvature: simplicial_curvature

# Data definition
parameters:
  data_domain: graph
  data_type: manual_dataset
  data_name: manual
  data_dir: ${paths.data_dir}${dataset.parameters.data_domain}/${dataset.parameters.data_type}
  #data_split_dir: ${paths.data_dir}data_splits/${dataset.parameters.data_name}

  # Dataset parameters
  num_features: 1
  num_classes: 2
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: node
  data_seed: 0
  split_type: k-fold #'k-fold' # either k-fold or test
  k: 10 # for k-Fold Cross-Validation

  # Dataloader parameters
  batch_size: 1 # Fixed
  num_workers: 1
  pin_memory: False
