_target_: topobenchmarkx.io.load.loaders.GraphLoader

defaults:
  - /transforms/transform_chain2(g2s)

# Data definition
parameters:
  data_domain: graph
  data_type: TUDataset
  data_name: MUTAG
  data_dir: ${paths.data_dir}${dataset.parameters.data_domain}/${dataset.parameters.data_type}/${dataset.parameters.data_name}
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.parameters.data_name}/train_prop=0.5

  # Dataset parameters
  num_features: 7 # here basically I specify the initial num features in mutang at x aka x_0
  num_classes: 2
  task: classification
  task_level: graph
  data_seed: 0

  # Dataloader parameters
  batch_size: 1 # We have an issue with allowing multiple graphs in a batch due to sparse incidences
  num_workers: 0
  pin_memory: False

# transform:
#   _target_: topobenchmarkx.transforms.lifting.DataLiftingTransform
#   lifting: CellCyclesLifting
#   k_value: 1
#   complex_dim: 2
#   max_triangles: 6
#   aggregation_method: "sum"