transform_type: 'lifting'
transform_name: "HypergraphFormanRicciCurvatureLifting"
network_type: 'weighted'
threshold_type: 'quantile'
threshold_direction: 'above'
threshold: 0.1
feature_lifting: ProjectionSum
preserve_edge_attr: False
complex_dim: 1
neighborhoods: ${oc.select:model.backbone.neighborhoods,null}