defaults:
  - model_checkpoint
  # - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: ${get_monitor_metric:${dataset.parameters.task},${dataset.parameters.loss_type}} #
  mode: "${get_monitor_mode:${dataset.parameters.task}}"
  save_last: False
  auto_insert_metric_name: False

early_stopping:
  monitor: ${callbacks.model_checkpoint.monitor}
  patience: 25
  mode: ${callbacks.model_checkpoint.mode}

model_summary:
  max_depth: -1

learning_rate_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: "epoch"