defaults:
  - model_checkpoint
  # - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: val/${dataset.parameters.loss_type} #
  mode: "min"
  save_last: False
  auto_insert_metric_name: False

early_stopping:
  monitor: val/${dataset.parameters.loss_type}
  patience: 25
  mode: "min"

model_summary:
  max_depth: -1

learning_rate_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: "epoch"