# Dataset loader config
loader:
  _target_: topobenchmarkx.data.load.loaders.GraphLoader
  parameters: 
    data_domain: graph
    data_type: cornel
    data_name: US-county-demos
    year: 2012
    task_variable: 'MedianIncome' # options: ['Election', 'MedianIncome', 'MigraRate', 'BirthRate', 'DeathRate', 'BachelorRate', 'UnemploymentRate']
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  num_features: 6
  max_node_degree: 20
  num_classes: 1
  task: regression
  loss_type: mse
  monitor_metric: mae
  task_level: node

#splits
split_params:
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random #'k-fold' # either "k-fold" or "random" strategies
  k: 10 # for "k-fold" Cross-Validation
  train_prop: 0.5 # for "random" strategy splitting

# Dataloader parameters
dataloader_params:
  batch_size: 1 # Fixed
  num_workers: 1
  pin_memory: False
