_target_: topobenchmarkx.models.network_module.NetworkModule

feature_encoder:
  _target_: topobenchmarkx.models.encoders.default_encoders.BaseFeatureEncoder
  in_channels: ${infer_in_channels:${dataset}} #${dataset.parameters.num_features}
  out_channels: 32
  selected_dimensions:
    - 0
    - 1

backbone:
  _target_: topomodelx.nn.cell.can.CAN
  in_channels_0: ${model.feature_encoder.out_channels}
  in_channels_1: ${model.feature_encoder.out_channels}
  out_channels: ${model.feature_encoder.out_channels}
  dropout: 0.5
  heads: 4 # For now we stuck to out_channels//heads
  concat: True
  skip_connection: True
  n_layers: 2
  att_lift: False

loss:
  _target_: topobenchmarkx.models.losses.loss.DefaultLoss
  task: ${dataset.parameters.task}
  loss_type: ${dataset.parameters.loss_type}

# evaluator:
#   _target_: topobenchmarkx.evaluators.evaluator.Evaluator
#   metrics: [acc, rocauc]

readout:
  _target_: topobenchmarkx.models.readouts.default_readouts.GNNBatchReadOut
  task_level: ${dataset.parameters.task_level}
  in_channels: ${parameter_multiplication:${model.backbone.out_channels},${model.backbone.heads}}
  out_channels: ${dataset.parameters.num_classes}

# readout_workaround:
#   _target_: topobenchmarkx.models.readout_workaround.ReadOutWorkaround
#   backbone_outputs: ["x_0"]


backbone_wrapper:
  _target_: topobenchmarkx.models.wrappers.default_wrapper.CANWrapper
  _partial_: true

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 50
  gamma: 0.5

# compile model for faster training with pytorch 2.0
compile: false
