_target_: topobenchmarkx.models.network_module.NetworkModule

backbone:
  _target_: topomodelx.nn.cell.ccxn.CCXN
  in_channels_0: ${dataset.parameters.num_features}
  in_channels_1: ${dataset.parameters.num_features}
  in_channels_2: ${dataset.parameters.num_features}
  n_layers: 2
  att: True

loss:
  _target_: topobenchmarkx.models.losses.loss.DefaultLoss
  task: ${dataset.parameters.task}

readout:
  _target_: topobenchmarkx.models.readouts.default_readouts.NodeLevelReadOut
  task_level: ${dataset.parameters.task_level}
  in_channels: ${model.backbone.in_channels_0}
  out_channels: ${dataset.parameters.num_classes}

backbone_wrapper:
  _target_: topobenchmarkx.models.wrappers.default_wrapper.CCXNWrapper
  _partial_: true

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.1
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# compile model for faster training with pytorch 2.0
compile: false
